### ISSUE TITLE
"Alle Daten erlaubt" nicht möglich nach Umstellung von 141 auf 150

### ISSUE THREAD

**Issue by andre5tz** [terminal42/contao-calendarfield#15]
Hallo,

die Einstellung "Alle Daten erlaubt" für die Auswahl Datumsrichtung (datedirection) ist mit der Umstellung von Version 1.41 auf 1.5 nicht mehr möglich.

Wenn ich bei Datumsrichtung "Alle Daten erlaubt" einstelle und auf speichern gehe, dann wird automatisch die Einstellung auf "Nur Datum in der Zukunft (inkl. Heute)" umgestellt. Ich kann alle Einstellungen speichern bis auf die Möglichkeit, Daten aus der Vergangenheit wie auch aus der Zukunft auszuwählen. Das Problem kann ich umgehen, wenn ich auf die Version 1.41 downgrade.

Problem besteht bei Contao 3.2.13 und auch bei der Contao 3.3 COD.

Viele Grüße und vielen Dank.
André

**Comment by phreak** [comment]
bestätige auch: aöö-inkl.com, Contao 3.4.0

**Comment by cboelter** [comment]
I have the same problem.

**Comment by pagestyles** [comment]
Bestätige ich auch, 3.2.12 bei HostEurope
