### ISSUE TITLE
z-index in CSS einfügen

### ISSUE THREAD

**Issue by xantippe** [terminal42/contao-calendarfield#19]
Hi,

die "Kalenderauswahl-Popups" kommen bei mir in keiner Implementierung zum Vorschein - ich muss jedes Mal in der CSS ein z-index für ```datepicker_bootstrap``` nachtragen - da der Container "ganz oben" erscheinen soll, kann der Index ruhig hoch sein z.B. 1000

```
.datepicker_bootstrap {
    background-color: white;
    border: 1px solid #ccc;
    border-radius: 3px;
    box-shadow: 0 1px 6px rgba(0, 0, 0, 0.2);
    color: #000;
    font-size: 1em;
    line-height: normal;
    padding: 0.3em;
    position: absolute;
    width: 18em;
    z-index: 1000;
}
```

**Comment by aschempp** [comment]
Die Datei `.datepicker_bootstrap` unterliegt nicht unserer Kontrolle sondern wird vom Plugin geliefert. Dass du jedes mal `z-index` brauchst liegt wohl eher an deinem Design, darauf haben wir keinen Einfluss.

**Comment by xantippe** [comment]
... welches Plugin steckt genau dahinter -  Link?

**Comment by Toflar** [comment]
https://github.com/contao/core/tree/master/assets/mootools/datepicker/2.2.0

**Comment by xantippe** [comment]
ah... o.k. - ich dachte irgendwas "externes", Dank!
