### ISSUE TITLE
upgrade.php = update.php?

### ISSUE THREAD

**Issue by stefansl** [terminal42/contao-calendarfield#22]
I ran into this issue:
Failed opening required 'system/modules/calendarfield/config/upgrade.php' (include_path='.:/usr/share/pear/php5.3') in system/modules/calendarfield/config/runonce.php on line 26
There is no upgrade.php, but update.php

**Comment by christianbarkowsky** [comment]
Composer sowie RE.

Warning: require_once(/www/***/docs/system/modules/calendarfield/config/upgrade.php): failed to open stream: No such file or directory in system/modules/calendarfield/config/runonce.php on line 26
#0 system/modules/calendarfield/config/runonce.php(26): __error(2, 'require_once(/w...', '/www/breidenbac...', 26, Array)
#1 system/modules/calendarfield/config/runonce.php(26): Terminal42RunonceExecutorVersion100::run()
#2 system/modules/calendarfield/config/runonce.php(46): Terminal42RunonceExecutorVersion100->run(Array)
#3 system/modules/core/classes/Backend.php(119): include('/www/breidenbac...')
#4 system/modules/repository/classes/RepositoryManager.php(484): Contao\Backend->handleRunOnce()
#5 system/modules/repository/classes/RepositoryBackendModule.php(152): RepositoryManager->update('database')
#6 system/modules/core/classes/BackendModule.php(91): RepositoryBackendModule->compile()
#7 system/modules/repository/classes/RepositoryBackendModule.php(72): Contao\BackendModule->generate()
#8 system/modules/repository/classes/RepositoryManager.php(58): RepositoryBackendModule->generate()
#9 system/modules/core/classes/Backend.php(262): RepositoryManager->generate()
#10 contao/main.php(137): Contao\Backend->getBackendModule('repository_mana...')
#11 contao/main.php(288): Main->run()
#12 {main}

Fatal error: require_once(): Failed opening required '/www/***/docs/system/modules/calendarfield/config/upgrade.php' (include_path='.:/usr/share/php:/usr/share/pear') in /www/***/docs/system/modules/calendarfield/config/runonce.php on line 26

**Comment by 31er** [comment]
Gleiches Problem bei mir mit Contao 3.2.20.
Umbenennung der update.php in upgrade.php löste das Problem.

**Comment by aschempp** [comment]
I fixed the error in the extension repository, please download the latest build.
