### ISSUE TITLE
Datumsrichtung läßt sich mit 1.7.1 nicht mehr speichern

### ISSUE THREAD

**Issue by 31er** [terminal42/contao-calendarfield#23]
Die Auswahl der Datumsrichtung läßt sich mit Version 1.7.1 und 1.7.0 nicht mehr speichern. Es wird nur "Alle Daten erlaubt" gespeichert.

Ein Downgrade auf Version 1.6.2 Build 4 ermöglich das Feature wieder.

**Comment by aschempp** [comment]
Das liegt wohl am fehlenden DB-Update. Sollte mit 1.7.2 behoben sein.

**Comment by 31er** [comment]
Sorry, aber mit der Datumsrichtung funktioniert bei mir leider auch mit 1.7.2 unter Contao 3.2.20 mit dem alten ER (kein Composer) nicht. Egal was unter Datumsrichtung ausgewählt ist, es wird nach dem Speichern immer wieder auf „Alle Daten erlaubt“ zurückgesetzt und im FE sind alle Daten zugelassen.

Calendarfield deinstalliert, die Tabellen in der DB gelöscht, Systemwartung durchgeführt, Calendarfield neu installiert, Problem besteht weiterhin.

Installiere ich Calenderfield über die bereits installierte Version 1.7.2 drüber, kommt immer eine Datenbankaktualisierung der Tabelle datedirection:
ALTER TABLE `tl_form_field` CHANGE `dateDirection` `dateDirection` varchar(2) NOT NULL default '';

Was kann ich noch tun, damit die Datumrichtung auch mit 1.7.2 funktioniert?

**Comment by aschempp** [comment]
Vermutlich die database.sql im config-Verzeichnis löschen

**Comment by aschempp** [comment]
Der neuste Build im ER sollte das Problem beheben.

**Comment by 31er** [comment]
Vielen Dank für die Bemühungen.
Jetzt funktioniert es wieder.
