### ISSUE TITLE
jquery version

### ISSUE THREAD

**Issue by wiesson** [terminal42/contao-calendarfield#5]
Ist jetzt eigentlich kein Fehler, sondern eine Frage ;)

habt ihr in naher Zukunft geplant eine jQuery Variante ebenfalls einzubauen? Also je nach dem was im FE verwendet wird jQuery oder Mootools? 

jQuery Beispiel: http://amsul.github.com/pickadate.js/

**Comment by cliffparnitzky** [comment]
Eine jQuery Variante gibt es nun hier: https://github.com/hofff/contao-jcalendarfield
